sonar.projectKey=ReactLearn
# sonar-project.properties
sonar.projectKey=my-react-app
sonar.projectName=React App
sonar.sources=src,infra
sonar.exclusions=**/node_modules/**,**/dist/**
sonar.language=js
sonar.sourceEncoding=UTF-8

# Enable IaC scanning
sonar.inclusions=**/*.js,**/*.jsx,**/*.ts,**/*.tsx,**/*.tf,**/*.yaml,**/*.yml,**/Dockerfile
